### ISSUE TITLE
Dark Mode cutting into _post Text 

### ISSUE THREAD

**Issue by ChrisSidebotham** [samarsault/plainwhite-jekyll#77] opened 2020-08-19 19:49 UTC
I have a small issue in which if your tagline is 2 lines long (wrapped) then the post on screen gets cut in from the left 😢 it only does this when viewing a post in Dark Mode 
With 2 line tagline 
![image](https://user-images.githubusercontent.com/48600046/90682702-44a94000-e25d-11ea-9cb3-51a1f2f71e2f.png)

With single tagline 
![image](https://user-images.githubusercontent.com/48600046/90682731-538ff280-e25d-11ea-9912-419bc8598c66.png)

Hope this makes sense! 👍

**Comment by samarsault** [comment] 2020-08-19 21:30
I can't reproduce it, are you using the latest version?

**Comment by ChrisSidebotham** [comment] 2020-08-19 22:18
Hi Samarsault, I am using the version from your repo following the instructions of adding the following to the _config.yml 

```ruby:
remote_theme: samarsault/plainwhite-jekyll
plugins:
  - jekyll-feed

plainwhite: 
  name: Chris Sidebotham
  tagline: Cloud Advocate. Microsoft 365 Specialist
  portfolio_image:  "assets/Memoji.png" # the path from the directory of the site to the image to display (no / at the start)
  date_format: "%b %-d, %Y"
  dark_mode: true
  search: true
```

This only seems to appear when the tagline is 2 rows long e.g more than 25 characters long including spaces

**Comment by samarsault** [comment] 2020-08-20 06:17
<img width="466" alt="Screenshot 2020-08-20 at 11 46 49 AM" src="https://user-images.githubusercontent.com/2987087/90723699-dc993f00-e2da-11ea-9fa2-d19ca0a93b44.png">
Tried it with your configuration, looks fine.

**Comment by ChrisSidebotham** [comment] 2020-08-20 08:27
Ahh, It works fine on the home page - it only does it when you open a post itself 

![image](https://user-images.githubusercontent.com/48600046/90742338-54f60500-e2c7-11ea-8eeb-6af8f62045a8.png)

**Comment by samarsault** [comment] 2020-08-20 09:19
Ah you are right, thanks for pointing that out.
Fixed in https://github.com/samarsault/plainwhite-jekyll/commit/aed01f13025c866b4a4c2b84c33e58c0c4c37aaa.

**Closed** 2020-08-20 09:19 UTC
